alias s_exam='cd ~/Documents/S_Exam'
alias gitlog='git log --all --graph --decorate --oneline -n 30'
alias gs='git status'
alias chicago='cd ~/OneDrive\ -\ Aarhus\ universitet/Chicago'
alias note='cd ~/OneDrive\ -\ Aarhus\ universitet/Notes'
